<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month_Select_in_My_Calnder</name>
   <tag></tag>
   <elementGuidId>d6fe7adc-57f5-493b-8de6-685d872e3ab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.react-calendar__navigation__label__labelText--from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
