<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first element in dates of office hours</name>
   <tag></tag>
   <elementGuidId>92057f85-181b-451b-b8ea-bf3ba316ca7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fa0dc53-384a-4c66-83b9-ae5439cd0b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d70aecd5-fd49-4901-b30f-9bd7930b97f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8841ad89-c182-4ab2-bcc1-237863dc0ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-flex tw-h-[120px] tw-w-[88px] tw-flex-col tw-items-center tw-justify-center tw-rounded-[10px] max-sm:tw-h-[64px] max-sm:tw-w-[64px]  max-sm:tw-flex-none max-sm:tw-shadow-md tw-bg-[#1A428A] tw-text-white tw-text-center</value>
      <webElementGuid>7d2730c5-f563-4b0a-b77a-5d1516f4c233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09/11السبت</value>
      <webElementGuid>c9e51c0e-4e3a-4a92-ac5f-f6418e4f5db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-bg-[#F9F9F9] tw-px-5&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full tw-max-w-[1500px]&quot;]/div[@class=&quot;tw-pb-10 max-sm:tw-bg-white&quot;]/div[1]/div[@class=&quot;tw-mb-10 tw-flex max-sm:tw-mb-0  tw-justify-center tw-gap-6 tw-overflow-x-auto tw-px-5 tw-py-5&quot;]/button[@class=&quot;tw-flex tw-h-[120px] tw-w-[88px] tw-flex-col tw-items-center tw-justify-center tw-rounded-[10px] max-sm:tw-h-[64px] max-sm:tw-w-[64px]  max-sm:tw-flex-none max-sm:tw-shadow-md tw-bg-[#1A428A] tw-text-white tw-text-center&quot;]</value>
      <webElementGuid>0c6028c5-5d45-4fe1-ab50-fab401f10290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='date']</value>
      <webElementGuid>2f308e3c-4ac6-4779-8b51-a47cebfb45a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>1309b43b-129c-4b10-92e7-befa58ad7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر التاريخ'])[1]/following::button[1]</value>
      <webElementGuid>3cbb22e1-d985-4b87-a6de-2387d552ef21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر الاستاذ'])[1]/following::button[2]</value>
      <webElementGuid>e0a22a46-2fe0-4e39-9902-e9aed082b8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/preceding::button[1]</value>
      <webElementGuid>24dd0267-69c2-4b6d-b04c-bbfeec9610bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>3c5fb4b4-cdc5-4a2b-b986-05e60e20b1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'date' and (text() = '09/11السبت' or . = '09/11السبت')]</value>
      <webElementGuid>9ff5d220-fb01-4c5a-9d9d-b56d183fda49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
