<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first element office hour</name>
   <tag></tag>
   <elementGuidId>1d2e656d-a92a-4841-b3be-041592458321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;calendar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da26c3dc-43c9-43dd-89b7-c7339aff6d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>4881d8b9-56cd-41cc-a48f-4cbc92b66569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>f8050f85-67d5-4eae-9dd5-d65ee8953bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-h-[32px] tw-w-[231px] tw-self-center tw-rounded-lg tw-border tw-border-solid tw-border-[#1A428A] !tw-bg-transparent tw-text-[#1A428A] disabled:tw-cursor-not-allowed disabled:tw-border-gray-200 disabled:!tw-bg-gray-200 disabled:!tw-text-brand-blue/50 max-sm:tw-w-[160px]</value>
      <webElementGuid>8e7d84d9-1072-4275-ab0f-5ae664135ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضف الى رزنامتي</value>
      <webElementGuid>1e154c27-10b2-4447-903c-ca1514f0caf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] tw-relative !tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-bg-[#F9F9F9] tw-px-5&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full tw-max-w-[1500px]&quot;]/div[@class=&quot;tw-pb-10 max-sm:tw-bg-white&quot;]/section[@class=&quot;tw-flex tw-flex-wrap tw-items-center tw-justify-center tw-gap-4 tw-px-4&quot;]/div[@class=&quot;tw-flex tw-h-fit tw-w-[255px]  tw-flex-col tw-gap-4 tw-rounded-t-2xl tw-bg-white tw-p-4 max-sm:tw-shadow-[0px_4px_6px_0px_#0000001A]&quot;]/button[@class=&quot;tw-h-[32px] tw-w-[231px] tw-self-center tw-rounded-lg tw-border tw-border-solid tw-border-[#1A428A] !tw-bg-transparent tw-text-[#1A428A] disabled:tw-cursor-not-allowed disabled:tw-border-gray-200 disabled:!tw-bg-gray-200 disabled:!tw-text-brand-blue/50 max-sm:tw-w-[160px]&quot;]</value>
      <webElementGuid>8712e946-c5df-421c-8a2d-fb4a4fd0ba09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='calendar']</value>
      <webElementGuid>86a09b74-dc42-470f-aa57-0787e430efe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div/section/div/button</value>
      <webElementGuid>4a45a217-500d-4520-ab68-f3eb1aa831a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::button[1]</value>
      <webElementGuid>aea026a1-4786-4468-bbcf-a5844a0f9c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::button[2]</value>
      <webElementGuid>f70232c0-8631-430a-9c5e-a61c84d8e910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::button[3]</value>
      <webElementGuid>29f2efcd-5dc3-4b0d-a65e-634f806e7954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='روابط سريعة'])[1]/preceding::button[3]</value>
      <webElementGuid>a523e65c-3938-46c0-8783-47ed0122271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/button</value>
      <webElementGuid>c518e14e-d4b2-437e-9fa0-b529b38ef5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'calendar' and (text() = 'اضف الى رزنامتي' or . = 'اضف الى رزنامتي')]</value>
      <webElementGuid>d25ad4b0-6d6e-4f01-a878-3a932d6d377f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
