<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>second element office hour</name>
   <tag></tag>
   <elementGuidId>e7e758b6-d577-4852-b7c3-81739e7cf5ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>&#xd;
&#xd;
&#xd;
&#xd;
&#xd;
0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='calendar'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
